//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussPassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buscatg
    {
        public int BusID { get; set; }
        public Nullable<int> CompID { get; set; }
        public string CategName { get; set; }
    
        public virtual busCompany busCompany { get; set; }
        public virtual buses buses { get; set; }
    }
}
