//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussPassManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buses
    {
        public int BusID { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> Avail_seats { get; set; }
    
        public virtual buscatg buscatg { get; set; }
    }
}
