//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussPassManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class busspassdbEntities5 : DbContext
    {
        public busspassdbEntities5()
            : base("name=busspassdbEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<DriverInfo> DriverInfo { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<destination> destination { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<subscription> subscription { get; set; }
        public virtual DbSet<tbladmin> tbladmin { get; set; }
        public virtual DbSet<buscatg> buscatg { get; set; }
        public virtual DbSet<busCompany> busCompany { get; set; }
        public virtual DbSet<buses> buses { get; set; }
    }
}
